config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 resources :books
 root :to => redirect('/books')
 get '/books/:id/similar_books' => 'books#search_similar_books', as: :search_similar_books
end

app/models/book.rb
class Book < ActiveRecord::Base


  def self.all_genres ; %w[Science\ fiction Drama Action\ and\ romance Romance Mystery Horror] ; end

  validates :genre, :inclusion => {:in => Book.all_genres }


    def self.similar_books(book)
        Book.where author: book.author
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 def index
    if !params.key?(:genres)
        params[:genres] = {}
    end

    permitted = params.permit(:sort, genres: params[:genres].keys)
    sort = permitted[:sort] || session[:sort]

    case sort
    when 'title'
     ordering,@title_header = {:title => :asc}, 'hilite'
    when 'genre'
     ordering,@genre_header = {:genre => :asc}, 'hilite'
    end

    @all_genres = Book.all_genres
    @selected_genres = permitted[:genres] || session[:genres] || {}

    if @selected_genres == {}
        @selected_genres = Hash[@all_genres.map {|genre| [genre, genre]}]
    end

    if permitted[:sort] != session[:sort] or permitted[:genres] != session[:genres]
        session[:sort] = sort
        session[:genres] = @selected_genres
        redirect_to :sort => sort, :genres => @selected_genres and return
    end

    @books = Book.where(genre: @selected_genres.keys).order(ordering)
 end

 def show
     id = params[:id]
     @book = Book.find(id)
 end

 def new
     @book = Book.new
 end

 def create
     params.require(:book)
     permitted = params[:book].permit(:author, :title, :genre, :isbn_number, :publish_date, :description)
     @book = Book.new(permitted)
     if @book.save
        flash[:notice] = "#{@book.title} was successfully created."
        redirect_to books_path
     else
        render 'new'
     end
 end

 def edit
     @book = Book.find(params[:id])
 end

 def update
     @book = Book.find params[:id]
     params.require(:book)
     permitted = params[:book].permit(:author, :title, :genre, :isbn_number, :publish_date, :description)
     if @book.update_attributes(permitted)
        flash[:notice] = "#{@book.title} was successfully updated."
        redirect_to book_path(@book)
     else
        render 'edit'
     end
 end

 def destroy
     @book = Book.find(params[:id])
     @book.destroy
     flash[:notice] = "Book '#{@book.title}' deleted."
     redirect_to books_path
 end
 def search_similar_books
   @book = Book.find(params[:id])
   if @book.author.nil? || @book.author.empty?
     flash[:warning]= "'#{@book.title}' has no author info"
     redirect_to books_path
   else
     @books = Book.similar_books(@book)
   end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.haml
%h2 Edit book


= form_tag book_path(@book), :method => :put do

  = label :book, :author, 'Author'
  = text_field :book, 'author'

  = label :book, :title, 'Title'
  = text_field :book, 'title'

  = label :book, :genre, 'Genre'
  = select :book, :genre, ["Science fiction", "Drama", "Action and romance", "Romance", "Mystery", "Horror"]

  = label :book, :isbn_number, 'ISBN Number'
  = text_field :book, 'isbn_number'

  = label :book, :publish_date, 'Released On'
  = date_select :book, :publish_date

  = label :book, :description, 'Description'
  = text_field :book, 'description'

  = submit_tag 'Update Book Info'

app/views/books/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Books

= form_tag books_path, :method => :get, :id => 'genres_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag "genre_sort", true if @genre_header
  Include:
  - @all_genres.each do |genre|
    = genre
    = check_box_tag "genres[#{genre}]", 1, @selected_genres.include?(genre), :id => "genres_#{genre}"
  = submit_tag 'Refresh', :id => 'genres_submit'

%table#books
  %thead
    %tr
      %th Author
      %th{:class => @title_header}= link_to 'Title', books_path(:sort => 'title'), :id => 'title_header'
      %th{:class => @genre_header}= link_to 'Genre', books_path(:sort => 'genre'), :id => 'genre_header'
      %th Description
      %th ISBN number
      %th Publish date
      %th 
  %tbody
    - @books.each do |book|
      %tr
        %td= book.author 
        %td= book.title 
        %td= book.genre
        %td= book.description
        %td= book.isbn_number
        %td= book.publish_date
        %td= link_to "More info", book_path(book)

= link_to 'Add new book', new_book_path

app/views/books/new.html.haml
%h2 Create New Book

= form_tag books_path, :method => :post do
  - unless @book.errors.empty?
    #warning
    Errors prevented this book from being #{controller.action_name}d:
    %ul
      - @movie.errors.full_messages.each do |error|
        %li= error

  = label :book, :author, 'Author'
  = text_field :author, 'author'

  = label :book, :title, 'Title'
  = text_field :book, 'title'

  = label :book, :genre, 'Genre'
  = select :book, :genre, ["Science fiction", "Drama", "Action and romance", "Romance", "Mystery", "Horror"]

  = label :book, :isbn_number, 'ISBN Number'
  = text_field :book, 'isbn_number'

  = label :book, :publish_date, 'Released On'
  = date_select :book, :publish_date

  = label :book, :description, 'Description'
  = text_field :book, 'description'

  = submit_tag 'Create book'

app/views/books/search_similar_books.html.haml
%h1 Similar Books page for #{@book.title}

%table#same_author
  %thead
    %tr
      %th Author
      %th Title
      %th Genre
      %th Description
      %th ISBN number
      %th Publish date
  %tbody
    - @books.each do |book|
      %tr
        %td= book.author 
        %td= book.title
        %td= book.genre
        %td= book.description
        %td= book.isbn_number
        %td= book.publish_date

app/views/books/show.html.haml
%h2 Details about #{@book.title}

%ul#details
  %li
    Author:
    = @book.author
  %li
    Genre:
    = @book.genre
  %li
    ISBN number:
    = @book.isbn_number

  %li
    Publish date:
    = @book.publish_date.strftime("%B %d, %Y")

%h3 Description:
%p#description= @book.description

= link_to 'Edit info', edit_book_path(@book)
= link_to 'Delete', book_path(@book), :method => :delete
= link_to 'Back to book list', books_path
= link_to 'Find Books With Same Author', search_similar_books_url(id: @book.id)

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title My Favourite Books
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    #main
      = yield